#!/usr/bin/python
import requests
import os
import shutil
import tempfile
import argparse
import sys
import tarfile
import subprocess
import datetime
import configparser
import warnings

AUR_URL = None
RPC_URL = None
OPTIONS = None
CONFIG = None

class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'


def argument_parse():   
    parser = argparse.ArgumentParser(
        description="Search for the pkg_name in the Arch User Repository",
        epilog="Get the latest version at https://github.com/Ezbob/PyAUR-Explorer")
    parser.add_argument("pkg_name", 
        help="Package name")
    parser.add_argument("-lp","--long-print", action="store_true", 
        help="Prints all info fields")
    parser.add_argument("-q","--quite", action="store_false", 
        help="Suppresses extra explanatory messages")
    parser.add_argument("-a","--all", action="store_true", 
        help="If no exact match is found, print all alternatives at once")
    parser.add_argument("-e","--entries-shown",type=int, default=4, 
        help="Set the maximum number of entries shown when showing alternatives. " 
        "This option gets ignored if all alternatives are set to be shown")
    parser.add_argument("-d","--download", action="store_true", 
        help="Download the package if a exact match was found")
    parser.add_argument("-o","--output",default="packages/", 
        help="Set the output directory for downloading packages. Default: packages/")
    parser.add_argument("-i","--install",action="store_true", 
        help="Download and install the package using makepkg")
    parser.add_argument("-u","--update", action="store_true",
        help="If package already exists in output directory, download it again")
    return parser.parse_args()


def consume_arguments():
    global OPTIONS
    args = argument_parse()
    OPTIONS = vars( args )
    return args.pkg_name


def open_get_request(url, params, stream=False):
    req = requests.get( url, params=params, stream=stream )
    req.raise_for_status()
    return req


def check_json(req):
    if req.headers['Content-Type'] == "application/json":
        return req.json()
    return req 

# valid types are 'search' and 'info'
def get_json_from_aur(pkg_name, request_type='search'):

    version = CONFIG.get('AURconnection', 'version', fallback="5")
    params = { 'v' : version }
    params['type'] = request_type
    params['arg'] = pkg_name
    json = check_json( open_get_request( RPC_URL, params ) )

    if json['type'] == "error":
        print(bcolors.FAIL + "Server returned an error:", json['error'], bcolors.ENDC)
        exit(1)
    else:
        return json['resultcount'], json['results']

def date_from_timestamp(timestamp):
    return datetime.datetime.fromtimestamp(
        int(timestamp)
    ).strftime('%H:%M %d-%m-%Y')

def ask( message ):
    return raw_input(message) if sys.version_info[0] == 2 else input(message)


def decode(message, encoding='utf-8'):
	return message.decode(encoding) if type(message) == bytes else message


def print_entry(entry):
    if OPTIONS['long_print']:
        print(bcolors.BOLD + decode(entry['Name']), bcolors.ENDC )
        for key, val in entry.items():
            if key == 'Name':
                continue
            if key == 'FirstSubmitted' or key == 'LastModified':
                print("\t{}{}{}: {}".format(bcolors.OKBLUE, key, bcolors.ENDC, date_from_timestamp(decode(val))))
            else:
                print("\t{}{}{}: {}".format(bcolors.OKBLUE, key, bcolors.ENDC, decode(val)))
    else:
        keys = ['Description', 'Maintainer', 'Version', 'Popularity']
        if entry['Name'] != None:
            print(bcolors.BOLD + decode(entry['Name']) + bcolors.ENDC)
        for key in keys:
            print("\t{}{}{}: {}".format(bcolors.OKBLUE, key, bcolors.ENDC, decode(entry[key])))


def show_alternatives(count, results):
    if OPTIONS['all']:
        for entry in results:
            print_entry(entry)
    else:
        step = OPTIONS['entries_shown']

        next_index = min( count, step )
        do_loop = True
        index = 0
        while do_loop:
            for index in range( index, next_index ):
                print_entry( results[index] )

            index += 1
            diff = count - index 
            
            if diff - 1 < step:
                next_index = count
            else:
                next_index += step
        
            if diff == 0:
                choice_msg = "No more entries. Press {}enter{} to exit.\n".format(bcolors.OKGREEN, bcolors.ENDC)
            else:
                choice_msg = "Press {}enter{} to show the next {} entries or {}ctrl-c{} to quit:\n"\
                    .format(bcolors.OKGREEN, bcolors.ENDC, diff, bcolors.FAIL, bcolors.ENDC)

            try:
                choice = ask(choice_msg).strip().lower()
            except KeyboardInterrupt as e:
                exit(0)

            if diff == 0:
                do_loop = False
               

def vprint(message):
    if OPTIONS['quite']:
        print(message)


def add_trailing_slash( path ):
    return path if path.endswith("/") else path + "/"


def check_or_make_out_dir():
    if not os.path.exists(OPTIONS['output']):
        os.mkdir(OPTIONS['output'])
    elif not os.path.isdir(OPTIONS['output']):
        print("Output directory chosen is not a directory. Exiting.")
        exit(1)
    return add_trailing_slash( OPTIONS['output'] )


def download_package(tar_url, file_path, chunk_size=64):
    download_url = AUR_URL + tar_url
    download_request = open_get_request( download_url, params={}, stream=True )

    with open(file_path, 'wb') as file:
        for chunk in download_request.iter_content(chunk_size):
            file.write(chunk)


def find_pkgbuild_file(path):
    for file in os.listdir(path):
        if file == "PKGBUILD":
            return True
    return False


def install_package(file_path):
    with tempfile.TemporaryDirectory() as temp_dir:

        shutil.copy(file_path, temp_dir)
        tar_filename = file_path.split("/")[-1]
        temp_path = add_trailing_slash(temp_dir) + tar_filename 

        with tarfile.open(temp_path) as tar_file:
            print("Package contains the following entries:")
            tar_file.list()

            choice = ask("\nProceed with extraction? [N,y] ").strip().lower()
            if choice == "y":
                vprint("Extracting...")
                tar_file.extractall( path=temp_dir )
                vprint("Extracted.")

                extracted_dir = add_trailing_slash(temp_dir) + tar_filename.split(".")[0]

                vprint("Installing using makepkg")
                os.chdir(extracted_dir)

                vprint("Searching for PKGBUILD file...")
                if not find_pkgbuild_file( extracted_dir ):
                    print("Error: could not find PKGBUILD exiting...")
          
                vprint("PKGBUILD found.")

                vprint("Parsing control to makepkg.")
                exitcode = subprocess.call(['makepkg', "-sir"])
                
                if exitcode == 0:
                    vprint("Installation was successful!")
                else:
                    vprint("Installation was unsuccessful.")


def direct_match(match_pkg):
    print_entry(match_pkg)
    filename = match_pkg['URLPath'].split('/')[-1]

    output_path = check_or_make_out_dir()
    file_path = output_path + filename
    do_download = OPTIONS['update'] or not (os.path.exists(file_path) and os.path.isfile(file_path))

    if OPTIONS['install']:
        print( "WARNING: Packages can contain malicious code. Install only from trusted sources." )
        choice = ask("Install package {} anyway? [N,y] ".format( match_pkg['Name'] ))
        if choice.strip().lower() == "y":
            if do_download:
                vprint("Downloading...")
                download_package(match_pkg['URLPath'], file_path)
                vprint("Downloaded. Saved as {}".format(file_path))
            else:
                vprint("Package already exists as {!r}".format(file_path))
            install_package( file_path )

    elif OPTIONS['download']:
        if do_download:
            choice = ask("Download {}? [N,y] ".format(filename))
            if choice.strip().lower() == "y":
                vprint("Downloading...")
                download_package(match_pkg['URLPath'], file_path)
                vprint("Downloaded. Saved as {}".format(file_path))
        else:
            vprint("Package already exists as {!r}".format(file_path))


def find_direct_match( results ):
    direct_pkg_result = None
    for result in results:
        if result['Name'] == package_name:
            direct_pkg_result = result
            results.remove(result)
            break
    return direct_pkg_result


def initialize_config():
    global CONFIG
    CONFIG = configparser.ConfigParser()
    CONFIG.read(['config.ini', os.path.expanduser('~/.config/pythur/config.ini')]) 
    if not CONFIG.sections():
        warnings.warn("No or empty configuration file detected")


if __name__ == '__main__':
    initialize_config()

    AUR_URL = CONFIG.get('connections', 'aurbaseurl', fallback='https://aur.archlinux.org')
    RPC_URL = AUR_URL + CONFIG.get('connections', 'rpcurl', fallback='/rpc')

    package_name = consume_arguments()

    direct_pkg_result = None
    count, results = get_json_from_aur( package_name )
    
    if count == 0:
        vprint(bcolors.FAIL + "No results found." + bcolors.ENDC)
    else:
        direct_pkg_result = find_direct_match(results)

        results = sorted(results, 
            key=lambda entry: entry['Popularity'], reverse=True) 

        if direct_pkg_result:
            vprint("Found a direct match:")
            direct_match( direct_pkg_result )
        else:
            vprint("Could not find a direct match. Found {} alternatives:".format(count))
            show_alternatives( count, results )

